[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.install]
cmds = ["cd back && mvn clean install -DskipTests"]

[phases.build]
cmds = ["cd back && mvn clean package -DskipTests"]

[start]
cmd = "cd back && java -jar target/back-0.0.1-SNAPSHOT.jar"

